//! Dictation history — storage trait + SQLite implementation.

use crate::error::AppError;

mod sqlite;
pub use sqlite::{SqliteHistoryStore, wall_clock_iso8601};

/// A stored dictation history entry (full record, with id).
#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct HistoryEntry {
    pub id: i64,
    pub text: String,
    pub raw_text: Option<String>,
    pub style: String,
    pub language: String,
    pub app_name: Option<String>,
    pub created_at: String, // ISO-8601 UTC, e.g. "2026-05-03T10:00:00Z"
    pub uuid: Option<String>,
    pub device_id: Option<String>,
    // Additive v2 fields (architecture.md §History-Schema)
    pub plugin_id: Option<String>,
    pub manifest_version: Option<String>,
    pub output_language: Option<String>,
}

/// Fields needed to persist a new entry (no id — generated by DB).
#[derive(Debug, Clone)]
pub struct NewHistoryEntry {
    pub text: String,
    pub raw_text: Option<String>,
    pub style: String,
    pub language: String,
    pub app_name: Option<String>,
    pub created_at: String, // ISO-8601 UTC
    pub uuid: Option<String>,
    pub device_id: Option<String>,
    pub plugin_id: Option<String>,
    pub manifest_version: Option<String>,
    pub output_language: Option<String>,
}

/// Storage backend for dictation history.
///
/// Implementations must be `Send + Sync + 'static` for DI-mockability.
/// All async fns return `AppError` on failure — callers decide whether to
/// surface the error or fail soft.
#[async_trait::async_trait]
pub trait HistoryBackend: Send + Sync + 'static {
    /// Persist a new dictation entry. Returns the new row's `id`.
    /// On `max_entries` exceeded: oldest entries are pruned atomically.
    async fn append(&self, entry: &NewHistoryEntry) -> Result<i64, AppError>;

    /// Load up to `limit` most-recent entries, newest first.
    async fn list(&self, limit: u32) -> Result<Vec<HistoryEntry>, AppError>;

    /// Delete entry by id. Idempotent (no-error on missing id).
    async fn delete(&self, id: i64) -> Result<(), AppError>;

    /// Delete all entries.
    async fn clear(&self) -> Result<(), AppError>;

    /// Total number of stored entries.
    async fn count(&self) -> Result<u32, AppError>;
}

/// No-op implementation for contexts where history is not available.
/// Used as fail-soft fallback when SqliteHistoryStore::open() fails at boot.
pub struct NullHistoryBackend;

#[async_trait::async_trait]
impl HistoryBackend for NullHistoryBackend {
    async fn append(&self, _entry: &NewHistoryEntry) -> Result<i64, AppError> {
        Ok(0)
    }
    async fn list(&self, _limit: u32) -> Result<Vec<HistoryEntry>, AppError> {
        Ok(vec![])
    }
    async fn delete(&self, _id: i64) -> Result<(), AppError> {
        Ok(())
    }
    async fn clear(&self) -> Result<(), AppError> {
        Ok(())
    }
    async fn count(&self) -> Result<u32, AppError> {
        Ok(0)
    }
}

pub mod keys {
    pub const DELETE_FAILED: &str = "error.history.delete_failed";
    pub const CLEAR_FAILED: &str = "error.history.clear_failed";
}
