// ATDD RED-PHASE SCAFFOLDS — Story 7.3 (Shared-core STT request + guard path via JNI)
// ----------------------------------------------------------------------------------
// Generated by bmad-testarch-atdd (2026-06-12). These are RED-phase acceptance tests:
// they assert the TARGET behavior and FAIL on the current implementation.
//
// This is a STAGING artifact, NOT compiled into the build. The dev-story (Task 3/4/5)
// drops each block into the real path, runs it RED, then implements until GREEN
// (the project's mandatory inversion-check / RED-first discipline).
//
// Stack: backend (Rust, inline #[cfg(test)]). No browser/E2E layer for this story.
// Bound to real paths per project-context rule (no parallel mocks).
//
// Legend:
//   [PROVEN-RED] = empirically run on current impl 2026-06-12, confirmed failing.
//   [NEEDS-SURFACE] = compiles+runs only after dev adds the new code (JNI fn / verbose_json
//                     parser). Until then it is a documented spec, not a live test.
//   [DEVICE] = integration test, runs on device/emulator over adb — NOT Linux `cargo test`.

// ============================================================================
// P0 · AC3 / R-002 — H14 whole-word match for single-word blocklist entries
// Target: src-tauri/src/stt/hallucination.rs  (mod tests)
// [PROVEN-RED 2026-06-12]: red_h14_whole_word_real_speech_not_blocked FAILED
//   ("Standard"/"Milliarde"/"Hardware" wrongly blocked by `contains("ard")`).
//   Control (red_control_ghosts_still_blocked) PASSED — discriminating, not blanket-flip.
// Green when: single-word entries match whole-word; multi-word stay substring (Task 3).
// ============================================================================
#[test]
fn h14_single_word_real_speech_not_blocked() {
    // Real words that merely CONTAIN a single-word blocklist entry ("ard", "zdf"...)
    assert!(!is_hallucination("Standard"), "contains 'ard' but is real speech");
    assert!(!is_hallucination("Milliarde"), "contains 'ard' but is real speech");
    assert!(!is_hallucination("Hardware"), "contains 'ard' but is real speech");
}

#[test]
fn h14_single_word_ghosts_still_blocked() {
    // Control: whole-word matches must STILL be killed after the fix.
    assert!(is_hallucination("ZDF"), "standalone ZDF stays blocked");
    assert!(is_hallucination("amara.org"), "amara.org stays blocked");
    assert!(is_hallucination("WDR 2021"), "WDR whole-word stays blocked");
}

#[test]
fn h14_multi_word_entries_stay_substring() {
    // Multi-word entries keep substring semantics (the existing contract).
    assert!(
        is_hallucination("Amara.org Community Subtitles"),
        "multi-word substring match preserved"
    );
}

// ============================================================================
// P1 · AC5 — Stockphrase family + length-independent trailing-ghost match
// Target: src-tauri/src/stt/hallucination.rs
// [PROVEN-RED 2026-06-12]: red_stockphrase_family_blocked and
//   red_trailing_ghost_on_long_clip_blocked both FAILED on current impl.
// Green when: stockphrase family added to blocklist AND the >8-word gate
//   (hallucination.rs:155-158) no longer suppresses the trailing-ghost/stockphrase
//   match — WITHOUT re-introducing false positives on generic single-word entries
//   in long real speech (shape per *design, AC5).
// ============================================================================
#[test]
fn stockphrase_family_blocked_short_clip() {
    assert!(is_hallucination("Groß- und Kleinschreibung"));
    assert!(is_hallucination("Untertitelung des ZDF, 2020"));
    assert!(is_hallucination("[Musik]"));
}

#[test]
fn trailing_ghost_on_long_clip_blocked() {
    // >8 words of real dictation ENDING in a trailing subtitle ghost (the ~1.1% case).
    assert!(is_hallucination(
        "Ich habe das ganze Dokument gelesen und es sieht wirklich gut aus Untertitelung des ZDF 2020"
    ));
}

#[test]
fn long_real_speech_with_incidental_term_still_passes() {
    // FALSE-POSITIVE GUARD (R-005): a long, genuine sentence that merely MENTIONS a
    // generic blocklist term must NOT be killed by the relaxed gate.
    assert!(!is_hallucination(
        "Ich habe heute beim ZDF angerufen und mit dem Redakteur ausführlich gesprochen"
    ));
}

// ============================================================================
// P1 · AC4 — Shared pre-STT silence/duration filter parity (boundary contract)
// Target: src-tauri/src/pipeline.rs (silence_skip / compute_wav_rms)
// [NEEDS-SURFACE for the exact API shape — read pipeline.rs and bind to the real fns.]
// Folds in SilencePreFilter.kt:19-23 contract. Boundaries: `<` not `<=`.
//   exactly MIN_RECORDING_MS  -> Pass
//   exactly SILENCE_THRESHOLD -> Pass
//   malformed WAV (RMS fails) -> skip silent check -> Pass
// Resolves Recall #1 (0.02f vs 0.005f self-desync) + M1 silenceThreshold config-read
// by construction (single Rust source). Lock with golden vectors (seed for 7.7).
// ============================================================================
// #[test] fn silence_pass_at_exact_min_recording_ms() { /* boundary == -> Pass */ }
// #[test] fn silence_pass_at_exact_threshold() { /* == SILENCE_THRESHOLD -> Pass */ }
// #[test] fn malformed_wav_skips_silent_check_and_passes() { /* RMS err -> Pass */ }

// ============================================================================
// P1 · AC1 (H3/Recall#5) — Prompt assembly is single-sourced in Rust
// Target: src-tauri/src/stt/mod.rs build_stt_prompt_with_hint (:112)
// Golden-vector: dictionary terms + language hint + customPrompt -> expected body.
// ============================================================================
// #[test] fn prompt_body_includes_dictionary_lang_hint_and_custom_prompt() { ... }

// ============================================================================
// P0 · AC6 / R-004 — verbose_json request + BOTH-SHAPE parse tolerance
// Target: src-tauri/src/stt/mod.rs (build_form :240 response_format; parse :303;
//         TranscriptionResponse :144). [NEEDS-SURFACE: segment parsing not yet present.]
// RED today: build_form emits response_format="json"; there is no segment-drop path.
// Note: TranscriptionResponse{text} already deserializes verbose_json (serde ignores
//   unknown fields) — so the .text path is NOT the regression risk; the NEW segment
//   parsing + drop logic is. Both `json` and `verbose_json` fixtures MUST parse
//   without panic (fail-soft) so the desktop pipeline (R-004) does not regress.
// Green when: verbose_json switch + tolerant segment parser + threshold drop (Task 5).
// ============================================================================
// #[test] fn build_form_requests_verbose_json() { /* assert response_format=verbose_json */ }
// #[test] fn parse_tolerates_legacy_json_response_shape() { /* {"text":"..."} -> Ok */ }
// #[test] fn parse_tolerates_verbose_json_with_segments() { /* full shape -> Ok, .text intact */ }
// #[test] fn parse_missing_segment_field_does_not_panic() { /* fail-soft, never panic */ }
// (Thresholds no_speech_prob/compression_ratio/avg_logprob are UNKNOWN — choose in dev
//  against recorded segment metadata, lock as golden vectors. Do NOT invent here — R-009.)

// ============================================================================
// P0 · AC10 / R-003 — JNI panic-safety (fail-soft, never panic into the JVM)
// Target: new src-tauri/src/stt/groq_jni.rs (#![cfg(target_os = "android")])
// [NEEDS-SURFACE: the JNI fn does not exist yet.] Mirror license/jni.rs:20-24 +
//   stt/jni_bridge.rs:30-36 convention: check every conversion, structured-error
//   string on failure, log::error!, never panic.
// Each malformed input class needs a fail-soft test:
//   - invalid base64 / non-UTF8 args        -> structured error string, no panic
//   - empty WAV byte[]                       -> structured error (mirror SttError::EmptyAudio)
//   - oversized WAV                          -> handled, no panic
//   - malformed Groq response               -> structured error, no panic
// Runnable on Linux as pure-Rust unit tests over the marshalling helpers IF the JNI fn
// is split so arg-decoding + error-mapping are testable without the JVM (testability
// rec #2). The thin jni-env layer is exercised by the [DEVICE] proof below.
// ============================================================================
// #[test] fn jni_invalid_base64_returns_structured_error_not_panic() { ... }
// #[test] fn jni_empty_wav_returns_structured_error() { ... }
// #[test] fn jni_malformed_response_fails_soft() { ... }

// ============================================================================
// P0 · AC1 / R-001 — Weg A PROOF: async Groq request over JNI (no Tokio runtime)
// [DEVICE] integration — runs on device/emulator over adb, NOT Linux `cargo test`.
// This is the residual gate (BLOCK downgraded to PROVE). The first dev step must show:
//   a per-call current-thread tokio runtime + block_on(WhisperStt::transcribe) runs
//   cleanly over the bridge from Kotlin's background thread (KlarvoOverlayService :897/
//   :1072/:1347) and returns a transcript. Request SHAPE is asserted device-free via
//   wiremock on the Rust side (ADR-0005 stack) so we don't need a live Groq call to
//   check the multipart body.
// If this fails -> ESCALATE (do not iterate blind). Contingency: time-boxed runtime
//   spike; fallback thin-Kotlin-HTTP-shim only with Andi's sign-off (degrades Hard Rule).
// ============================================================================
// #[test] fn weg_a_blockon_request_shape_via_wiremock() { /* Rust-side, device-free */ }
// (device) groq_over_jni_round_trip_returns_transcript_no_crash  // android instrumentation

// ============================================================================
// P2 · AC9 — ADR-0017 boundary: no Kotlin STT request/guard re-implementation survives
// CI grep gate (seeded here, enforced by Story 7.7). After Task 6 deletions, a grep for
// KlarvoApi.transcribe / buildMultipartBody / HallucinationFilter / SilencePreFilter
// in android/ returns nothing.
// ============================================================================
// (CI assertion, not a Rust unit test — see 7.7 parity net.)
