#!/usr/bin/env bash
# Build Klarvo for Android.
#
# gen/android/ is .gitignored and regenerated by `tauri android init`.
# This script patches everything that Tauri does not manage automatically:
#   - Kotlin sources (android/kotlin-src/ -> gen/android/)
#   - AndroidManifest.xml (permissions + service declarations)
#   - accessibility_service_config.xml (copied from android/res-xml/)
#   - strings.xml (app name + accessibility description)
#   - build.gradle.kts root (JitPack repo, Kotlin plugin version)
#   - app/build.gradle.kts (compileOptions, android-vad + coroutines deps)

set -euo pipefail
cd "$(dirname "$0")/.."

GEN_ANDROID="src-tauri/gen/android"

# ---------------------------------------------------------------------------
# 1. Kotlin sources
# ---------------------------------------------------------------------------
SRC="android/kotlin-src/com/klarvo/voice"
DST="$GEN_ANDROID/app/src/main/java/com/klarvo/voice"

if [ ! -d "$DST" ]; then
    echo "Error: $DST does not exist. Run 'npx tauri android init' first."
    exit 1
fi

echo "[sync] Copying Kotlin files from kotlin-src/ to gen/android/"
cp "$SRC"/*.kt "$DST/"
echo "[sync] Done: $(ls -1 "$SRC"/*.kt | wc -l) files copied"

# ---------------------------------------------------------------------------
# 2. accessibility_service_config.xml
# ---------------------------------------------------------------------------
XML_DST="$GEN_ANDROID/app/src/main/res/xml"
mkdir -p "$XML_DST"
if [ ! -f "$XML_DST/accessibility_service_config.xml" ]; then
    cp "android/res-xml/accessibility_service_config.xml" "$XML_DST/"
    echo "[sync] Copied accessibility_service_config.xml to res/xml/"
fi

# ---------------------------------------------------------------------------
# 3. strings.xml -- merge accessibility_service_description from source
# ---------------------------------------------------------------------------
STRINGS_GEN="$GEN_ANDROID/app/src/main/res/values/strings.xml"
# Rename Voxlit -> Klarvo if Tauri regenerated it with old name
if grep -q '>Voxlit<' "$STRINGS_GEN" 2>/dev/null; then
    sed -i 's/>Voxlit</>Klarvo</g' "$STRINGS_GEN"
    echo "[patch] Renamed Voxlit -> Klarvo in strings.xml"
fi
# Add accessibility_service_description if missing (not generated by Tauri)
if ! grep -q 'accessibility_service_description' "$STRINGS_GEN" 2>/dev/null; then
    DESCRIPTION=$(grep 'accessibility_service_description' "android/res-values/strings.xml" | sed 's/^[[:space:]]*//')
    sed -i "s|</resources>|    ${DESCRIPTION}\n</resources>|" "$STRINGS_GEN"
    echo "[patch] Added accessibility_service_description to strings.xml"
fi

# ---------------------------------------------------------------------------
# 4. AndroidManifest.xml -- permissions + services
# ---------------------------------------------------------------------------
MANIFEST="$GEN_ANDROID/app/src/main/AndroidManifest.xml"

# Permissions
for PERM in \
    "android.permission.RECORD_AUDIO" \
    "android.permission.MODIFY_AUDIO_SETTINGS" \
    "android.permission.SYSTEM_ALERT_WINDOW" \
    "android.permission.POST_NOTIFICATIONS" \
    "android.permission.FOREGROUND_SERVICE" \
    "android.permission.FOREGROUND_SERVICE_MICROPHONE" \
    "android.permission.REQUEST_IGNORE_BATTERY_OPTIMIZATIONS"
do
    if ! grep -q "\"$PERM\"" "$MANIFEST"; then
        sed -i "/<uses-permission android:name=\"android.permission.INTERNET\" \/>/a\\    <uses-permission android:name=\"$PERM\" />" "$MANIFEST"
        echo "[patch] Added permission $PERM to AndroidManifest.xml"
    fi
done

# KlarvoOverlayService
if ! grep -q 'KlarvoOverlayService' "$MANIFEST"; then
    OVERLAY_SERVICE='        <!-- Floating bubble overlay service (foreground, microphone type) -->\n        <service\n            android:name=".KlarvoOverlayService"\n            android:exported="false"\n            android:foregroundServiceType="microphone" />'
    sed -i "s|</application>|${OVERLAY_SERVICE}\n    </application>|" "$MANIFEST"
    echo "[patch] Added KlarvoOverlayService to AndroidManifest.xml"
fi

# KlarvoAccessibilityService
if ! grep -q 'KlarvoAccessibilityService' "$MANIFEST"; then
    ACCESS_SERVICE='        <!-- Accessibility service for system-wide keyboard detection and text paste -->\n        <service\n            android:name=".KlarvoAccessibilityService"\n            android:exported="true"\n            android:permission="android.permission.BIND_ACCESSIBILITY_SERVICE">\n            <intent-filter>\n                <action android:name="android.accessibilityservice.AccessibilityService" \/>\n            <\/intent-filter>\n            <meta-data\n                android:name="android.accessibilityservice"\n                android:resource="@xml\/accessibility_service_config" \/>\n        <\/service>'
    sed -i "s|</application>|${ACCESS_SERVICE}\n    </application>|" "$MANIFEST"
    echo "[patch] Added KlarvoAccessibilityService to AndroidManifest.xml"
fi

# ---------------------------------------------------------------------------
# 5. Root build.gradle.kts -- Kotlin plugin version + JitPack repo
# ---------------------------------------------------------------------------
GRADLE_ROOT="$GEN_ANDROID/build.gradle.kts"

# Bump Kotlin plugin 1.9.x -> 2.2.0 (matches stdlib pulled in by AGP 8.11.0)
if grep -q 'kotlin-gradle-plugin:1\.9' "$GRADLE_ROOT" 2>/dev/null; then
    sed -i 's/kotlin-gradle-plugin:1\.9[^"]*/kotlin-gradle-plugin:2.2.0/' "$GRADLE_ROOT"
    echo "[patch] Bumped kotlin-gradle-plugin to 2.2.0"
fi

# Add JitPack to allprojects.repositories (needed for android-vad)
if ! grep -q 'jitpack.io' "$GRADLE_ROOT" 2>/dev/null; then
    sed -i '/allprojects {/{
        n
        /repositories {/{
            n
            /google()/{
                a\        maven { url = uri("https://jitpack.io") }
            }
        }
    }' "$GRADLE_ROOT"
    echo "[patch] Added JitPack repository to build.gradle.kts"
fi

# ---------------------------------------------------------------------------
# 6. app/build.gradle.kts -- compileOptions + dependencies
# ---------------------------------------------------------------------------
APP_GRADLE="$GEN_ANDROID/app/build.gradle.kts"

# compileOptions block (Java 8 bytecode compatibility)
if ! grep -q 'compileOptions' "$APP_GRADLE" 2>/dev/null; then
    sed -i '/kotlinOptions {/i\    compileOptions {\n        sourceCompatibility = JavaVersion.VERSION_1_8\n        targetCompatibility = JavaVersion.VERSION_1_8\n    }' "$APP_GRADLE"
    echo "[patch] Added compileOptions to app/build.gradle.kts"
fi

# Coroutines dependency
if ! grep -q 'kotlinx-coroutines-android' "$APP_GRADLE" 2>/dev/null; then
    sed -i '/implementation("com.google.android.material/a\    implementation("org.jetbrains.kotlinx:kotlinx-coroutines-android:1.8.1")' "$APP_GRADLE"
    echo "[patch] Added kotlinx-coroutines-android dependency"
fi

# android-vad (Silero VAD for AUTOSTOP/AUTO recording modes)
if ! grep -q 'android-vad' "$APP_GRADLE" 2>/dev/null; then
    sed -i '/implementation("com.google.android.material/a\    implementation("com.github.gkonovalov.android-vad:silero:2.0.10")' "$APP_GRADLE"
    echo "[patch] Added android-vad:silero dependency"
fi

# ---------------------------------------------------------------------------
# 7. ProGuard keep-rules for our Kotlin classes
# ---------------------------------------------------------------------------
PROGUARD="$GEN_ANDROID/app/proguard-rules.pro"
if ! grep -q 'com.klarvo.voice' "$PROGUARD" 2>/dev/null; then
    cat >> "$PROGUARD" <<'RULES'

# Klarvo -- keep all custom classes (services, recorder, API, views)
-keep class com.klarvo.voice.** { *; }
RULES
    echo "[patch] Added ProGuard keep-rules for com.klarvo.voice"
fi

# ---------------------------------------------------------------------------
# 8. Environment
# ---------------------------------------------------------------------------
export JAVA_HOME="/usr/lib/jvm/java-17-openjdk-amd64"
export ANDROID_HOME="/home/andyon2/workspace/tools/android-sdk"
export NDK_HOME="/home/andyon2/workspace/tools/android-sdk/ndk/27.0.12077973"
export CC_aarch64_linux_android="$NDK_HOME/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android24-clang"
export AR_aarch64_linux_android="$NDK_HOME/toolchains/llvm/prebuilt/linux-x86_64/bin/llvm-ar"
# bindgen (used by whisper-rs-sys) requires a host libclang; use the one bundled in NDK
export LIBCLANG_PATH="$NDK_HOME/toolchains/llvm/prebuilt/linux-x86_64/musl/lib"
# cmake + ninja are required by whisper-rs-sys; use the ones from the Android SDK
export PATH="/home/andyon2/workspace/tools/android-sdk/cmake/3.22.1/bin:$PATH"
# cmake Android platform module requires ANDROID_NDK_ROOT to locate the toolchain
export ANDROID_NDK_ROOT="$NDK_HOME"
# whisper-rs-sys uses the cmake Rust crate, which reads CMAKE_TOOLCHAIN_FILE_<target>
# to pass the NDK toolchain to cmake (required for Android cross-compilation).
# We use a wrapper toolchain that forces ANDROID_ABI=arm64-v8a (otherwise cmake
# defaults to armeabi-v7a, producing 32-bit objects incompatible with the aarch64 linker).
WRAPPER_TOOLCHAIN="/tmp/android-aarch64-toolchain.cmake"
cat > "$WRAPPER_TOOLCHAIN" << 'TOOLCHAIN_EOF'
set(ANDROID_ABI "arm64-v8a" CACHE STRING "" FORCE)
set(ANDROID_PLATFORM "android-24" CACHE STRING "" FORCE)
TOOLCHAIN_EOF
# shellcheck disable=SC2016
echo 'include("$ENV{NDK_HOME}/build/cmake/android.toolchain.cmake")' >> "$WRAPPER_TOOLCHAIN"
export CMAKE_TOOLCHAIN_FILE_aarch64_linux_android="$WRAPPER_TOOLCHAIN"
# whisper-rs-sys forwards all CMAKE_* env vars as cmake -D defines.
# Force ARM NEON + dotprod for ggml/whisper.cpp. Without this, ggml
# cross-compiles without SIMD and runs 10-50x slower on ARM64.
export CMAKE_C_FLAGS="-DANDROID -ffunction-sections -fdata-sections -fPIC -w -march=armv8.2-a+dotprod+fp16"
export CMAKE_CXX_FLAGS="-DANDROID -ffunction-sections -fdata-sections -fPIC -w -march=armv8.2-a+dotprod+fp16"
# Also set the generator so cmake uses ninja (bundled in SDK cmake bin)
export CMAKE_GENERATOR_aarch64_linux_android="Ninja"

# ---------------------------------------------------------------------------
# 9. Build
# ---------------------------------------------------------------------------
VERSION=$(grep -m1 '"version"' src-tauri/tauri.conf.json | sed 's/.*"\([0-9.]*\)".*/\1/')
echo "[build] Starting Android build v${VERSION}..."
npx tauri android build --target aarch64

# ---------------------------------------------------------------------------
# 10. Sign + deploy
# ---------------------------------------------------------------------------
APK_IN="$GEN_ANDROID/app/build/outputs/apk/universal/release/app-universal-release-unsigned.apk"
APK_ALIGNED="/tmp/klarvo-aligned.apk"
TIMESTAMP=$(date +%Y%m%d-%H%M)
APK_DIR="/mnt/d/Dropbox/App Development/klarvo/releases/v${VERSION}"
mkdir -p "$APK_DIR"
APK_OUT="$APK_DIR/Klarvo-v${VERSION}-${TIMESTAMP}.apk"

echo "[sign] Aligning and signing APK..."
"$ANDROID_HOME/build-tools/34.0.0/zipalign" -f -p 4 "$APK_IN" "$APK_ALIGNED"
"$ANDROID_HOME/build-tools/34.0.0/apksigner" sign \
    --ks voxlit-debug.keystore \
    --ks-pass pass:dikta123 \
    --key-pass pass:dikta123 \
    --out "$APK_OUT" \
    "$APK_ALIGNED"

echo "[done] APK ready at: $APK_OUT"
