#!/usr/bin/env bash
# Build Klarvo for Android.
# Copies Kotlin source files from android/kotlin-src/ to gen/android/ before building,
# because Tauri does not manage custom Kotlin files automatically.

set -euo pipefail
cd "$(dirname "$0")/.."

# --- Sync Kotlin sources ---
SRC="android/kotlin-src/com/voxlit/voice"
DST="src-tauri/gen/android/app/src/main/java/com/voxlit/voice"

if [ ! -d "$DST" ]; then
    echo "Error: $DST does not exist. Run 'npx tauri android init' first."
    exit 1
fi

echo "[sync] Copying Kotlin files from kotlin-src/ to gen/android/"
cp "$SRC"/*.kt "$DST/"
echo "[sync] Done: $(ls -1 "$SRC"/*.kt | wc -l) files copied"

# --- Patch Gradle config ---
# gen/android/ is .gitignored and regenerated by `tauri android init`.
# Tauri generates kotlin-gradle-plugin:1.9.25, but AGP 8.11.0 + AndroidX
# pull in kotlin-stdlib:2.2.0 transitively → version mismatch.
# This patch ensures the Kotlin compiler matches the stdlib version.
GRADLE_ROOT="src-tauri/gen/android/build.gradle.kts"
if grep -q 'kotlin-gradle-plugin:1.9' "$GRADLE_ROOT" 2>/dev/null; then
    sed -i 's/kotlin-gradle-plugin:1\.9[^""]*/kotlin-gradle-plugin:2.2.0/' "$GRADLE_ROOT"
    echo "[patch] Bumped kotlin-gradle-plugin to 2.2.0 in build.gradle.kts"
fi

# Ensure compileOptions block exists in app/build.gradle.kts (Java bytecode compat)
APP_GRADLE="src-tauri/gen/android/app/build.gradle.kts"
if ! grep -q 'compileOptions' "$APP_GRADLE" 2>/dev/null; then
    sed -i '/kotlinOptions {/i\    compileOptions {\n        sourceCompatibility = JavaVersion.VERSION_1_8\n        targetCompatibility = JavaVersion.VERSION_1_8\n    }' "$APP_GRADLE"
    echo "[patch] Added compileOptions to app/build.gradle.kts"
fi

# Patch app name: Tauri generates "Voxlit" from the identifier, not from productName.
STRINGS_XML="src-tauri/gen/android/app/src/main/res/values/strings.xml"
if grep -q '>Voxlit<' "$STRINGS_XML" 2>/dev/null; then
    sed -i 's/>Voxlit</>Klarvo</g' "$STRINGS_XML"
    echo "[patch] Renamed app from Voxlit to Klarvo in strings.xml"
fi

# --- Set up environment ---
export JAVA_HOME="/usr/lib/jvm/java-17-openjdk-amd64"
export ANDROID_HOME="/home/andyon2/android-sdk"
export NDK_HOME="/home/andyon2/android-sdk/ndk/27.0.12077973"
export CC_aarch64_linux_android="$NDK_HOME/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android24-clang"
export AR_aarch64_linux_android="$NDK_HOME/toolchains/llvm/prebuilt/linux-x86_64/bin/llvm-ar"

# --- Build ---
echo "[build] Starting Android build..."
npx tauri android build --target aarch64

# --- Read version ---
VERSION=$(grep -m1 '"version"' src-tauri/tauri.conf.json | sed 's/.*"\([0-9.]*\)".*/\1/')
echo "[version] Building v${VERSION}"

# --- Sign + deploy ---
APK_IN="src-tauri/gen/android/app/build/outputs/apk/universal/release/app-universal-release-unsigned.apk"
APK_ALIGNED="/tmp/voxlit-aligned.apk"
APK_DIR="/mnt/d/Dropbox/App Development/klarvo/releases/v${VERSION}"
mkdir -p "$APK_DIR"
APK_OUT="$APK_DIR/Klarvo-v${VERSION}.apk"

echo "[sign] Aligning and signing APK..."
"$ANDROID_HOME/build-tools/34.0.0/zipalign" -f -p 4 "$APK_IN" "$APK_ALIGNED"
"$ANDROID_HOME/build-tools/34.0.0/apksigner" sign \
    --ks voxlit-debug.keystore \
    --ks-pass pass:dikta123 \
    --key-pass pass:dikta123 \
    --out "$APK_OUT" \
    "$APK_ALIGNED"

echo "[done] APK ready at: $APK_OUT"
