#!/usr/bin/env bash
# Build Klarvo for Android.
#
# gen/android/ is .gitignored and regenerated by `tauri android init`.
# This script patches everything that Tauri does not manage automatically:
#   - Kotlin sources (android/kotlin-src/ -> gen/android/)
#   - AndroidManifest.xml (permissions + service declarations)
#   - accessibility_service_config.xml (copied from android/res-xml/)
#   - strings.xml (app name + accessibility description)
#   - build.gradle.kts root (JitPack repo, Kotlin plugin version)
#   - app/build.gradle.kts (compileOptions, android-vad + coroutines deps)

set -euo pipefail
cd "$(dirname "$0")/.."

# --- Argument parsing -------------------------------------------------------
#   --clean   force a fresh recompile (defeats cargo/gradle incremental
#             staleness), mirrors sync-and-build.ps1 -Clean. Use when a SOURCE
#             change MUST land in the APK and you suspect a cached object/class.
CLEAN=0
for arg in "$@"; do
    case "$arg" in
        --clean) CLEAN=1 ;;
        *) echo "Unbekanntes Argument: $arg (erlaubt: --clean)"; exit 2 ;;
    esac
done

# --- Fail loudly ------------------------------------------------------------
# A half-finished build must NOT masquerade as success. The signed APK carries a
# fresh timestamp in its NAME even when gradle/cargo silently reused stale
# objects -- so a swallowed error would look like a brand-new build. We stamp the
# unsigned APK before/after the build and refuse to call it fresh unless the
# timestamp actually advanced. (Same lesson as the Windows stale-binary smoke
# failure, Story 1.2, 2026-05-31.)
fail() {
    echo ""
    echo "────────────────────────────────────────────────────────────"
    echo "  ANDROID-BUILD ABGEBROCHEN: $*"
    echo "  Es wurde KEINE neue APK erzeugt. Die zuletzt im Release-"
    echo "  Ordner liegende Datei ist NICHT dieser Build -- nicht aufs"
    echo "  Gerät schieben, nicht smoke-testen."
    echo "────────────────────────────────────────────────────────────"
    exit 1
}
trap 'fail "Unerwarteter Fehler (Zeile $LINENO) -- siehe Ausgabe oben."' ERR

GEN_ANDROID="src-tauri/gen/android"

# ---------------------------------------------------------------------------
# 1. Kotlin sources
# ---------------------------------------------------------------------------
SRC="android/kotlin-src/com/klarvo/voice"
DST="$GEN_ANDROID/app/src/main/java/com/klarvo/voice"

if [ ! -d "$DST" ]; then
    echo "Error: $DST does not exist. Run 'npx tauri android init' first."
    exit 1
fi

echo "[sync] Copying Kotlin files from kotlin-src/ to gen/android/"
cp "$SRC"/*.kt "$DST/"
echo "[sync] Done: $(ls -1 "$SRC"/*.kt | wc -l) files copied"

# ---------------------------------------------------------------------------
# 1b. Font resources (Geist + Geist Mono)
# ---------------------------------------------------------------------------
FONT_DST="$GEN_ANDROID/app/src/main/res/font"
FONT_SRC="android/res-font"
mkdir -p "$FONT_DST"
echo "[sync] Copying font resources from android/res-font/ to gen/android/"
shopt -s nullglob
FONT_FILES=("$FONT_SRC"/*.ttf)
shopt -u nullglob
[ "${#FONT_FILES[@]}" -gt 0 ] || fail "keine Fonts in $FONT_SRC/ — TTF-Dateien fehlen."
cp "${FONT_FILES[@]}" "$FONT_DST/"
echo "[sync] Done: ${#FONT_FILES[@]} font files copied"

# ---------------------------------------------------------------------------
# 2. accessibility_service_config.xml
# ---------------------------------------------------------------------------
XML_DST="$GEN_ANDROID/app/src/main/res/xml"
mkdir -p "$XML_DST"
if [ ! -f "$XML_DST/accessibility_service_config.xml" ]; then
    cp "android/res-xml/accessibility_service_config.xml" "$XML_DST/"
    echo "[sync] Copied accessibility_service_config.xml to res/xml/"
fi

# ---------------------------------------------------------------------------
# 3. strings.xml -- merge accessibility_service_description from source
# ---------------------------------------------------------------------------
STRINGS_GEN="$GEN_ANDROID/app/src/main/res/values/strings.xml"
# Rename Voxlit -> Klarvo if Tauri regenerated it with old name
if grep -q '>Voxlit<' "$STRINGS_GEN" 2>/dev/null; then
    sed -i 's/>Voxlit</>Klarvo</g' "$STRINGS_GEN"
    echo "[patch] Renamed Voxlit -> Klarvo in strings.xml"
fi
# Add accessibility_service_description if missing (not generated by Tauri)
if ! grep -q 'accessibility_service_description' "$STRINGS_GEN" 2>/dev/null; then
    DESCRIPTION=$(grep 'accessibility_service_description' "android/res-values/strings.xml" | sed 's/^[[:space:]]*//')
    sed -i "s|</resources>|    ${DESCRIPTION}\n</resources>|" "$STRINGS_GEN"
    echo "[patch] Added accessibility_service_description to strings.xml"
fi

# ---------------------------------------------------------------------------
# 4. AndroidManifest.xml -- permissions + services
# ---------------------------------------------------------------------------
MANIFEST="$GEN_ANDROID/app/src/main/AndroidManifest.xml"

# Permissions
for PERM in \
    "android.permission.RECORD_AUDIO" \
    "android.permission.MODIFY_AUDIO_SETTINGS" \
    "android.permission.SYSTEM_ALERT_WINDOW" \
    "android.permission.POST_NOTIFICATIONS" \
    "android.permission.FOREGROUND_SERVICE" \
    "android.permission.FOREGROUND_SERVICE_MICROPHONE" \
    "android.permission.REQUEST_IGNORE_BATTERY_OPTIMIZATIONS"
do
    if ! grep -q "\"$PERM\"" "$MANIFEST"; then
        sed -i "/<uses-permission android:name=\"android.permission.INTERNET\" \/>/a\\    <uses-permission android:name=\"$PERM\" />" "$MANIFEST"
        echo "[patch] Added permission $PERM to AndroidManifest.xml"
    fi
done

# KlarvoOverlayService
if ! grep -q 'KlarvoOverlayService' "$MANIFEST"; then
    OVERLAY_SERVICE='        <!-- Floating bubble overlay service (foreground, microphone type) -->\n        <service\n            android:name=".KlarvoOverlayService"\n            android:exported="false"\n            android:foregroundServiceType="microphone" />'
    sed -i "s|</application>|${OVERLAY_SERVICE}\n    </application>|" "$MANIFEST"
    echo "[patch] Added KlarvoOverlayService to AndroidManifest.xml"
fi

# KlarvoAccessibilityService
if ! grep -q 'KlarvoAccessibilityService' "$MANIFEST"; then
    ACCESS_SERVICE='        <!-- Accessibility service for system-wide keyboard detection and text paste -->\n        <service\n            android:name=".KlarvoAccessibilityService"\n            android:exported="true"\n            android:permission="android.permission.BIND_ACCESSIBILITY_SERVICE">\n            <intent-filter>\n                <action android:name="android.accessibilityservice.AccessibilityService" \/>\n            <\/intent-filter>\n            <meta-data\n                android:name="android.accessibilityservice"\n                android:resource="@xml\/accessibility_service_config" \/>\n        <\/service>'
    sed -i "s|</application>|${ACCESS_SERVICE}\n    </application>|" "$MANIFEST"
    echo "[patch] Added KlarvoAccessibilityService to AndroidManifest.xml"
fi

# ---------------------------------------------------------------------------
# 5. Root build.gradle.kts -- Kotlin plugin version + JitPack repo
# ---------------------------------------------------------------------------
GRADLE_ROOT="$GEN_ANDROID/build.gradle.kts"

# Bump Kotlin plugin 1.9.x -> 2.2.0 (matches stdlib pulled in by AGP 8.11.0)
if grep -q 'kotlin-gradle-plugin:1\.9' "$GRADLE_ROOT" 2>/dev/null; then
    sed -i 's/kotlin-gradle-plugin:1\.9[^"]*/kotlin-gradle-plugin:2.2.0/' "$GRADLE_ROOT"
    echo "[patch] Bumped kotlin-gradle-plugin to 2.2.0"
fi

# Add JitPack to allprojects.repositories (needed for android-vad)
if ! grep -q 'jitpack.io' "$GRADLE_ROOT" 2>/dev/null; then
    sed -i '/allprojects {/{
        n
        /repositories {/{
            n
            /google()/{
                a\        maven { url = uri("https://jitpack.io") }
            }
        }
    }' "$GRADLE_ROOT"
    echo "[patch] Added JitPack repository to build.gradle.kts"
fi


# ---------------------------------------------------------------------------
# 6. app/build.gradle.kts -- compileOptions + dependencies
# ---------------------------------------------------------------------------
APP_GRADLE="$GEN_ANDROID/app/build.gradle.kts"

# compileOptions block (Java 8 bytecode compatibility)
if ! grep -q 'compileOptions' "$APP_GRADLE" 2>/dev/null; then
    sed -i '/kotlinOptions {/i\    compileOptions {\n        sourceCompatibility = JavaVersion.VERSION_1_8\n        targetCompatibility = JavaVersion.VERSION_1_8\n    }' "$APP_GRADLE"
    echo "[patch] Added compileOptions to app/build.gradle.kts"
fi

# buildFeatures { buildConfig = true } -- required for BuildConfig.VERSION_NAME etc.
if ! grep -q 'buildFeatures' "$APP_GRADLE" 2>/dev/null; then
    sed -i '/kotlinOptions {/{
        n
        /jvmTarget/a\    }\n    buildFeatures {\n        buildConfig = true
    }' "$APP_GRADLE"
    echo "[patch] Added buildFeatures { buildConfig = true } to app/build.gradle.kts"
fi

# Coroutines dependency
if ! grep -q 'kotlinx-coroutines-android' "$APP_GRADLE" 2>/dev/null; then
    sed -i '/implementation("com.google.android.material/a\    implementation("org.jetbrains.kotlinx:kotlinx-coroutines-android:1.8.1")' "$APP_GRADLE"
    echo "[patch] Added kotlinx-coroutines-android dependency"
fi

# android-vad (Silero VAD for AUTOSTOP/AUTO recording modes)
if ! grep -q 'android-vad' "$APP_GRADLE" 2>/dev/null; then
    sed -i '/implementation("com.google.android.material/a\    implementation("com.github.gkonovalov.android-vad:silero:2.0.10")' "$APP_GRADLE"
    echo "[patch] Added android-vad:silero dependency"
fi

# ---------------------------------------------------------------------------
# 7. ProGuard keep-rules for our Kotlin classes
# ---------------------------------------------------------------------------
PROGUARD="$GEN_ANDROID/app/proguard-rules.pro"
if ! grep -q 'com.klarvo.voice' "$PROGUARD" 2>/dev/null; then
    cat >> "$PROGUARD" <<'RULES'

# Klarvo -- keep all custom classes (services, recorder, API, views)
-keep class com.klarvo.voice.** { *; }
RULES
    echo "[patch] Added ProGuard keep-rules for com.klarvo.voice"
fi

# ---------------------------------------------------------------------------
# 8. Environment
# ---------------------------------------------------------------------------
export JAVA_HOME="/usr/lib/jvm/java-17-openjdk-amd64"
export ANDROID_HOME="/home/andyon2/workspace/tools/android-sdk"
export NDK_HOME="/home/andyon2/workspace/tools/android-sdk/ndk/27.0.12077973"
export CC_aarch64_linux_android="$NDK_HOME/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android24-clang"
export AR_aarch64_linux_android="$NDK_HOME/toolchains/llvm/prebuilt/linux-x86_64/bin/llvm-ar"
# bindgen (used by whisper-rs-sys) requires a host libclang; use the one bundled in NDK
export LIBCLANG_PATH="$NDK_HOME/toolchains/llvm/prebuilt/linux-x86_64/musl/lib"
# cmake + ninja are required by whisper-rs-sys; use the ones from the Android SDK
export PATH="/home/andyon2/workspace/tools/android-sdk/cmake/3.22.1/bin:$PATH"
# cmake Android platform module requires ANDROID_NDK_ROOT to locate the toolchain
export ANDROID_NDK_ROOT="$NDK_HOME"
# whisper-rs-sys uses the cmake Rust crate, which reads CMAKE_TOOLCHAIN_FILE_<target>
# to pass the NDK toolchain to cmake (required for Android cross-compilation).
# We use a wrapper toolchain that forces ANDROID_ABI=arm64-v8a (otherwise cmake
# defaults to armeabi-v7a, producing 32-bit objects incompatible with the aarch64 linker).
WRAPPER_TOOLCHAIN="/tmp/android-aarch64-toolchain.cmake"
cat > "$WRAPPER_TOOLCHAIN" << 'TOOLCHAIN_EOF'
set(ANDROID_ABI "arm64-v8a" CACHE STRING "" FORCE)
set(ANDROID_PLATFORM "android-24" CACHE STRING "" FORCE)
TOOLCHAIN_EOF
# shellcheck disable=SC2016
echo 'include("$ENV{NDK_HOME}/build/cmake/android.toolchain.cmake")' >> "$WRAPPER_TOOLCHAIN"
export CMAKE_TOOLCHAIN_FILE_aarch64_linux_android="$WRAPPER_TOOLCHAIN"
# whisper-rs-sys forwards all CMAKE_* env vars as cmake -D defines.
# Force ARM NEON + dotprod for ggml/whisper.cpp. Without this, ggml
# cross-compiles without SIMD and runs 10-50x slower on ARM64.
export CMAKE_C_FLAGS="-DANDROID -ffunction-sections -fdata-sections -fPIC -w -march=armv8.2-a+dotprod+fp16"
export CMAKE_CXX_FLAGS="-DANDROID -ffunction-sections -fdata-sections -fPIC -w -march=armv8.2-a+dotprod+fp16"
# Also set the generator so cmake uses ninja (bundled in SDK cmake bin)
export CMAKE_GENERATOR_aarch64_linux_android="Ninja"

# ---------------------------------------------------------------------------
# 9. Build
# ---------------------------------------------------------------------------
VERSION=$(grep -m1 '"version"' src-tauri/tauri.conf.json | sed 's/.*"\([0-9.]*\)".*/\1/')

# The unsigned APK this build is expected to (re)produce. We stamp it before and
# after to prove the build actually re-emitted it (the freshness gate).
APK_IN="$GEN_ANDROID/app/build/outputs/apk/universal/release/app-universal-release-unsigned.apk"
apk_before=$( [ -f "$APK_IN" ] && stat -c %Y "$APK_IN" || echo 0 )

if [ "$CLEAN" -eq 1 ]; then
    echo "[clean] --clean: cargo clean -p klarvo + drop stale unsigned APK"
    ( cd src-tauri && cargo clean -p klarvo ) || true
    rm -f "$APK_IN"
    apk_before=0
fi

echo "[build] Starting Android build v${VERSION}..."
npx tauri android build --target aarch64 \
    || fail "tauri android build fehlgeschlagen (Exit $?) -- scroll hoch zum Compiler-/Gradle-Fehler."

# Prove this run actually produced a fresh unsigned APK.
[ -f "$APK_IN" ] || fail "tauri-Build lief durch, aber $APK_IN existiert nicht."
apk_after=$(stat -c %Y "$APK_IN")
if [ "$apk_after" -le "$apk_before" ]; then
    echo ""
    echo "[warn] Unsigned-APK-Zeitstempel UNVERÄNDERT -- gradle/cargo hat inkrementell"
    echo "       nichts neu gebaut. Entweder hat sich seit dem letzten Build nichts"
    echo "       geändert, oder ein Objekt/Class wurde aus dem Cache wiederverwendet."
    echo "       Soll eine QUELLÄNDERUNG in diesem Build landen: erneut mit  --clean ."
fi

# ---------------------------------------------------------------------------
# 10. Sign + deploy + verify
# ---------------------------------------------------------------------------
APK_ALIGNED="/tmp/klarvo-aligned.apk"
TIMESTAMP=$(date +%Y%m%d-%H%M)
APK_DIR="/mnt/d/Dropbox/App Development/klarvo/releases/v${VERSION}"
mkdir -p "$APK_DIR" || fail "Release-Ordner nicht anlegbar: $APK_DIR (ist D:/Dropbox gemountet?)."
APK_OUT="$APK_DIR/Klarvo-v${VERSION}-${TIMESTAMP}.apk"

echo "[sign] Aligning and signing APK..."
"$ANDROID_HOME/build-tools/34.0.0/zipalign" -f -p 4 "$APK_IN" "$APK_ALIGNED" \
    || fail "zipalign fehlgeschlagen."
"$ANDROID_HOME/build-tools/34.0.0/apksigner" sign \
    --ks voxlit-debug.keystore \
    --ks-pass pass:dikta123 \
    --key-pass pass:dikta123 \
    --out "$APK_OUT" \
    "$APK_ALIGNED" \
    || fail "apksigner sign fehlgeschlagen."

# --- Checkup: signed APK must exist, be non-empty, and verify ---------------
[ -s "$APK_OUT" ] || fail "Signiertes APK fehlt oder ist 0 Byte: $APK_OUT"
"$ANDROID_HOME/build-tools/34.0.0/apksigner" verify "$APK_OUT" \
    || fail "apksigner verify schlug fehl -- APK ist nicht gültig signiert."

size_mb=$(awk "BEGIN{printf \"%.1f\", $(stat -c %s "$APK_OUT")/1048576}")
echo ""
echo "════════════════════════════════════════════════════════════"
echo "  BUILD OK (Android) — frisch verifiziert."
echo "  APK     : $APK_OUT"
echo "  Version : v${VERSION}"
echo "  gebaut  : $(date -d @"$apk_after" '+%Y-%m-%d %H:%M:%S')"
echo "  Größe   : ${size_mb} MB"
echo "  signiert: ja (apksigner verify bestanden)"
echo "════════════════════════════════════════════════════════════"
