//! `xtask bindings-drift` — Drift-Check: failt wenn `shells/windows/src/bindings/index.ts`
//! nicht synchron mit dem aktuellen `generate-bindings`-Output ist (FR33).
//!
//! Implements Preventive Enforcement + Forcing-Sentinel per `memory/feedback_ci_gate_philosophy`.
//!
//! # Comparison Strategy
//!
//! Byte-identity: committed file content vs. freshly generated content from `render()`.
//! No whitespace normalisation or prettier pass — format drift is itself a bug.
//! (see Story 5.2 AC-E)
//!
//! # Side-Effect Handling
//!
//! `generate_bindings::render()` invokes `export-bindings` which overwrites `index.ts`.
//! This module snapshots the committed content before calling `render()`, compares after,
//! and restores the snapshot if drift is detected — ensuring `bindings-drift` is a pure check
//! with no permanent side effects on the committed file.

use std::process::ExitCode;

use crate::generate_bindings;

pub fn run() -> ExitCode {
    let bindings_path = generate_bindings::bindings_path();

    let committed = match std::fs::read_to_string(&bindings_path) {
        Ok(s) => s,
        Err(e) => {
            eprintln!(
                "bindings-drift: cannot read {}: {e}",
                bindings_path.display()
            );
            return ExitCode::from(2);
        }
    };

    let generated = match generate_bindings::render() {
        Ok(s) => s,
        Err(e) => {
            // render() overwrote index.ts before failing — restore the committed content.
            let _ = generate_bindings::write_to_disk(&committed);
            eprintln!("bindings-drift: render failed: {e}");
            return ExitCode::from(2);
        }
    };

    // byte-identity: see Story 5.2 AC-E
    if committed == generated {
        println!("bindings-drift: OK — index.ts is in sync with generate-bindings output");
        ExitCode::SUCCESS
    } else {
        // Restore committed file — drift check must not permanently modify the committed file.
        let _ = generate_bindings::write_to_disk(&committed);

        let committed_len = committed.len();
        let generated_len = generated.len();
        eprintln!("bindings drift detected");
        eprintln!("  file: {}", bindings_path.display());
        eprintln!("  committed: {committed_len} bytes, generated: {generated_len} bytes");
        eprintln!(
            "  run `cargo xtask generate-bindings` and commit the updated bindings"
        );
        ExitCode::from(1)
    }
}

#[cfg(test)]
mod tests {
    /// Forcing sentinel: proves bindings-drift catches artificial drift (CI-gate-philosophy).
    ///
    /// Tests the byte-identity comparison logic directly without invoking `export-bindings`.
    /// The RAII temp-file guard ensures the temp file is cleaned up even if the test panics.
    #[test]
    fn artificial_drift_detected() {
        use std::io::Write;

        let generated = "// This file has been generated by Tauri Specta. Do not edit this file manually.\nexport const foo = 'bar';";

        // Create a temp file with artificial modification (+1 comment line).
        let mut temp = tempfile::NamedTempFile::new().expect("temp file");
        let modified = format!("{generated}\n// artificial drift\n");
        temp.write_all(modified.as_bytes()).expect("write");
        temp.flush().expect("flush");

        let committed = std::fs::read_to_string(temp.path()).expect("read committed");

        // byte-identity: committed (modified) != generated → drift detected.
        assert_ne!(
            committed, generated,
            "artificial drift: modified content must differ from generated"
        );
    }

    /// Proves the comparison logic accepts equal content as in-sync.
    #[test]
    fn in_sync_returns_no_drift() {
        let content = "// same content on both sides";
        // byte-identity: same string on both sides = no drift.
        assert_eq!(content, content, "identical content = in-sync");
    }
}
