//! `xtask bindings-drift` — Drift-Check: failt wenn `shells/windows/src/bindings/index.ts`
//! nicht synchron mit dem aktuellen `generate-bindings`-Output ist (FR33).
//!
//! Implements Preventive Enforcement + Forcing-Sentinel per `memory/feedback_ci_gate_philosophy`.
//!
//! # Comparison Strategy
//!
//! Byte-identity: committed file content vs. freshly generated content from `render()`.
//! No whitespace normalisation or prettier pass — format drift is itself a bug.
//! (see Story 5.2 AC-E)
//!
//! # Side-Effect Handling
//!
//! `generate_bindings::render()` invokes `export-bindings` which overwrites `index.ts`.
//! This module snapshots the committed content before calling `render()`, compares after,
//! and restores the snapshot if drift is detected — ensuring `bindings-drift` is a pure check
//! with no permanent side effects on the committed file.

use std::path::Path;
use std::process::ExitCode;

use crate::generate_bindings;

pub fn run() -> ExitCode {
    let bindings_path = generate_bindings::bindings_path();

    let committed = match std::fs::read_to_string(&bindings_path) {
        Ok(s) => s,
        Err(e) => {
            eprintln!(
                "bindings-drift: cannot read {}: {e}",
                bindings_path.display()
            );
            return ExitCode::from(2);
        }
    };

    let generated = match generate_bindings::render() {
        Ok(s) => s,
        Err(e) => {
            // render() overwrote index.ts before failing — restore the committed content.
            if let Err(restore_err) = generate_bindings::write_to_disk(&committed) {
                eprintln!(
                    "bindings-drift: WARN — restore after render failure also failed: {restore_err}"
                );
                eprintln!(
                    "  {} may be in an inconsistent state",
                    bindings_path.display()
                );
            }
            eprintln!("bindings-drift: render failed: {e}");
            return ExitCode::from(2);
        }
    };

    // byte-identity: see Story 5.2 AC-E
    let in_sync = check_drift(&committed, &generated, &bindings_path);

    if in_sync {
        ExitCode::SUCCESS
    } else {
        // Restore committed file — drift check must not permanently modify the committed file.
        if let Err(restore_err) = generate_bindings::write_to_disk(&committed) {
            eprintln!(
                "bindings-drift: WARN — restore after drift detection failed: {restore_err}"
            );
            eprintln!(
                "  {} now contains the regenerated content",
                bindings_path.display()
            );
        }
        ExitCode::from(1)
    }
}

/// Pure byte-identity comparison + reporting. Returns `true` when in-sync, `false` on drift.
///
/// No I/O — prints to stdout/stderr only. Extracted so the forcing-sentinel tests can call
/// the production comparison logic directly: if `committed == generated` is inverted, both
/// `artificial_drift_detected` and `in_sync_returns_no_drift` regressions would surface.
fn check_drift(committed: &str, generated: &str, bindings_path: &Path) -> bool {
    if committed == generated {
        println!("bindings-drift: OK — index.ts is in sync with generate-bindings output");
        true
    } else {
        eprintln!("bindings drift detected");
        eprintln!("  file: {}", bindings_path.display());
        eprintln!(
            "  committed: {} bytes, generated: {} bytes",
            committed.len(),
            generated.len()
        );
        eprintln!("  run `cargo xtask generate-bindings` and commit the updated bindings");
        false
    }
}

#[cfg(test)]
mod tests {
    use super::check_drift;
    use std::path::Path;

    /// Forcing sentinel — calls the production comparison logic directly.
    /// If `committed == generated` were inverted to `committed != generated`, this fails.
    #[test]
    fn artificial_drift_detected() {
        let committed =
            "// generated by Tauri Specta\nexport const foo = 'bar';\n// artificial drift\n";
        let generated = "// generated by Tauri Specta\nexport const foo = 'bar';\n";
        let path = Path::new("dummy/index.ts");

        assert!(
            !check_drift(committed, generated, path),
            "drift must be detected when committed != generated"
        );
    }

    /// Forcing sentinel — calls the production comparison logic directly.
    /// If `committed == generated` were inverted, this also fails.
    #[test]
    fn in_sync_returns_no_drift() {
        let content = "// generated by Tauri Specta\nexport const foo = 'bar';";
        let path = Path::new("dummy/index.ts");

        assert!(
            check_drift(content, content, path),
            "identical content must report in-sync"
        );
    }
}
